baseURL = "https://www.wadearmstrong.com/"
languageCode = "en-us"
title = "Wade Armstrong"
theme = "AllinOne"

canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3


pygmentsuseclasses         = true


[permalinks]
  blog                     = "posts/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Posts"
    weight                 = -120
    identifier             = "posts"
    url                    = "posts/"

  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"



[params]
  faviconfile              = "logos/default_trans_80x80.png"               # from static/
  avatar                   = "headshots/wade_close.jpg"             # path to image in static dir e.g img/avatar.png
  author                   = "Wade Armstrong"
  author_intro             = "Hi, I'm Wade Armstrong"
  description              = "I'm a Developer & Engineering Manager who builds high-performing, quality-focused, happy teams. I love to travel, eat all the things — cook them too! — and take photos of it all."           # appears in the site header when set to a non-empty string
  images                   = ["headshots/wade_smiling.jpg"]
  welcome_head             = "Great to meet you!"
  welcome_word             = "<p>Do you need a technically-strong Lead to bring your team together and build quality, while still writing code? I've worked at scale (tens of millions of pageviews per day) and starting from zero. I'm passionate about Agile approaches, cross-functional teamwork, and building an inclusive and diverse culture. As a leader on software teams, I've mentored junior team members, turned around failed processes, and advocated for quality throughout the organization.</p>"
  googleAnalytics          = "UA-31586977-2"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "static/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "header-slides"    # path to image in static dir (for static pages)

  # highlighting
  highlightjs              = true

  # latex
  katex                    = true

  # links
  github                   = "//github.com/juniorbird"
  linkedin                 = "//linkedin.com/in/wadearmstrong"
  twitter                  = "//twitter.com/kaizendad"
  instagram                = "//instagram.com/kaizendad"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
